version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-3
    ECR_REPO: nginx-image
    AWS_ACCOUNT_ID: 044221706886   # Your AWS Account ID for ECR login & push
    IMAGE_NAME: container-5-1-26             # Container name used in imagedefinitions.json

phases:
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' \
        $IMAGE_NAME \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG \
        > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - scripts/**/*
